title: Responsive Starter
description: Minimal responsive + image optimization starter (2025)
theme: null
markdown: kramdown
plugins: []
url: "https://michalaferber.github.io"
baseurl: "/responsive-starter-repo"
exclude:
  - .github
  - README.md
  - node_modules
sass:
  style: compressed
